version: "3.7"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mnt/disks/sdb2/posts:/data/db
    networks:
      - tumblr-app

  tumblr-to-vk-app:
    build: .
    env_file:
      - .env
    volumes:
      - ./mnt/disks/sdb2/posts
    depends_on:
      - mongo
    networks:
      - tumblr-app

networks:
  tumblr-app:
    driver: bridge
