apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-tumblr-pvc
  namespace: applications
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 6Gi